version: '3'

services:
  freepbx:
    image: tiredofit/freepbx:latest
    platform: linux/amd64
    container_name: hazel-freepbx
    volumes:
      - ./data/freepbx:/data
      - ./data/certs:/certs
      - ./data/logs:/var/log/asterisk
      - ../scripts:/scripts
    ports:
      # Web interface (HTTP/HTTPS)
      - "8080:80"       # Web interface - Changed to 8080 to avoid conflicts with local web servers
      - "8443:443"     # Web interface (SSL) - Changed to 8443 to avoid conflicts
      # SIP Protocol (UDP/TCP)
      - "5060:5060/udp" # SIP
      - "5060:5060/tcp" # SIP
      # RTP Media ports
      - "10000-10100:10000-10100/udp" # RTP ports
      # IAX2 Protocol (optional)
      - "4569:4569/udp" # IAX2 protocol
      # PJSIP Protocol (optional)
      - "5061:5061/tcp" # SIP-TLS
    env_file:
      - ../passwords/passwords.env
    environment:
      # Database settings
      - DB_EMBEDDED=TRUE
      - DB_ROOT_PASS=MySQLRoot2025!
      - DB_PASS=FreePBXDB2025!
      - DB_USER=freepbxuser
      - DB_NAME=freepbx
      # Admin credentials
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=HazelPBX2025!
      # System settings
      - ENABLE_CRON=TRUE
      - ENABLE_SMTP=FALSE
      - TZ=America/New_York
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/admin/config.php"]
      interval: 60s
      timeout: 10s
      retries: 5
    networks:
      - hazel-network
    
  hazel-tts:
    build:
      context: ../
      dockerfile: docker/Dockerfile.tts
    container_name: hazel-tts
    volumes:
      - ./data/tts:/app/data
      - ./data/logs:/app/logs
      - ../scripts:/app/scripts
    ports:
      - "7850:5000"   # Expose the STT/TTS API service (remapped to 7850 to avoid conflicts)
    env_file:
      - ../passwords/passwords.env
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - freepbx
    restart: unless-stopped
    networks:
      - hazel-network

networks:
  hazel-network:
    driver: bridge
