version: '3'

services:
  freepbx:
    image: tiredofit/freepbx:latest
    privileged: true
    ports:
      # Web interface
      - "80:80"
      - "443:443"
      # SIP ports
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "5160:5160/tcp"
      - "5160:5160/udp"
      # IAX ports
      - "4569:4569/tcp"
      - "4569:4569/udp"
      # RTP ports
      # - "16384-16484:16384-16484/udp"
      - "10000-20000:10000-20000"
    volumes:
      - freepbx_certs:/certs
      - varvol:/var/
      - etcvol:/etc/asterisk
      - usrvol:/usr/lib64/asterisk
    env_file:
      - ../passwords/passwords.env
    environment:
      - TIMEZONE=America/New_York
      - ADMIN_DIRECTORY=admin
      - DB_EMBEDDED=TRUE
      - DB_NAME=asterisk
      - DB_USER=freepbx
      - DB_PASS=FreePBXDB2025!
      - ENABLE_HTTPS=TRUE
      - ENABLE_FAIL2BAN=FALSE
      - UCP_FIRST=FALSE
    restart: unless-stopped
    networks:
      - freepbx-network

  hazel-tts:
    build:
      context: ../
      dockerfile: docker/Dockerfile.tts
    volumes:
      - ./data/tts:/app/data
      - ./data/logs:/app/logs
      - ../scripts:/app/scripts
      - ../the-tendril-456617-g9-ffa050d985df.json:/gcloud/creds.json:ro
    ports:
      - "7850:5000"
    env_file:
      - ../passwords/passwords.env
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/gcloud/creds.json
    depends_on:
      - freepbx
    restart: unless-stopped
    networks:
      - freepbx-network

networks:
  freepbx-network:
    driver: bridge

volumes:
  freepbx_certs:
  varvol:
  etcvol:
  usrvol:
